GShop/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GShopConnection;
using GShopBus.Bus;

namespace GShop.Controllers
{
    public class BrandController : Controller
    {
        //
        // GET: /Brand/
        public ActionResult Index()
        {
            return View(BrandBus.List());
        }
	}
}

GShop/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GShopConnection;
using GShopBus.Bus;

namespace GShop.Controllers
{
    public class CategoryController : Controller
    {
        //
        // GET: /Category/
        public ActionResult Index()
        {
            return View(CategoryBus.List());
        }

        //public ActionResult XemSachTheoChuDe(int id)
        //{
        //    var db = new BookShopConnectionDB();
        //    IEnumerable<Sach> sach = db.Query<Sach>("Select * From Sach Where MaChuDe=@0", id);
        //    return View(sach);
        //}
        //public ActionResult Details(int id)
        //{
        //    BookShopConnection.ChuDe cd = ChuDeBUS.GetById(id);

        //    return View(cd);
        //}
	}
}

GShop/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GShopBus;
using GShopBus.Bus;

namespace GShop.Controllers
{
    public class ProductController : Controller
    {
        //
        // GET: /Product/
        public ActionResult Index()
        {
            return View(ProductBus.List());
        }

        //
        // GET: /Product/Details/5
        public ActionResult Details(int id)
        {
            return View(ProductBus.GetById(id));
        }

        //
        // GET: /Product/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Product/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Product/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Product/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Product/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Product/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult ViewProductByCatId(int id)
        {
            return View(ProductBus.LoadByCatId(id));
        }
        public ActionResult ViewProductByBraId(int id)
        {
            return View(ProductBus.LoadByBraId(id));
        }
    }
}

GShop/Views/Product/Index.cshtml
@model IEnumerable<GShopConnection.product>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_GShopLayout.cshtml";
}
<div class="col-sm-3">
    <div class="left-sidebar">
        <h2>Category</h2>
        <div class="panel-group category-products" id="accordian">
            <!--category-productsr-->            
            @Html.Action("Index", "Category")
        </div><!--/category-products-->

        <div class="brands_products">
            <!--brands_products-->
            <h2>Brands</h2>
            <div class="brands-name">
                <ul class="nav nav-pills nav-stacked">
                   @Html.Action("Index", "Brand")
                </ul>
            </div>
        </div><!--/brands_products-->

        <div class="price-range">
            <!--price-range-->
            <h2>Price Range</h2>
            <div class="well text-center">
                <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2"><br />
                <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
            </div>
        </div><!--/price-range-->

        <div class="shipping text-center">
            <!--shipping-->
            <img src="~/Assets/images/home/shipping.jpg" alt="" />
        </div><!--/shipping-->

    </div>
</div>
<div class="col-sm-9 padding-right">
    <div class="features_items">
        <!--features_items-->
        <h2 class="title text-center">Features Items</h2>
        @foreach (var item in Model)
        {
    <div class="col-sm-3">
        <div class="product-image-wrapper">
            <div class="single-products">
                <div class="productinfo text-center simpleCart_shelfItem">
                    <img src="@Url.Content("~/Assets/"+ @item.Image)" />
                    <h2 class="item_price">@String.Format(System.Globalization.CultureInfo.GetCultureInfo("vi-VN"), "{0:C0}", @item.Price)</h2>
                    <p style="min-height:50px" class="">@item.ProName</p>
                    <a href="#" class="btn btn-default add-to-cart item_add"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                    <a href="@Url.Action("Details", "Product", new { id = item.ProID})" class="btn btn-default add-to-cart"><span class="glyphicon glyphicon-list" aria-hidden="true"></span></a>
                </div>
            </div>
        </div>
    </div>
        }
    </div><!--features_items-->

    <div class="category-tab">
        <!--category-tab-->
        
    </div><!--/category-tab-->

    <div class="recommended_items">
        <!--recommended_items-->
        
    </div><!--/recommended_items-->

</div>

GShop/Views/Product/ViewProductByBraId.cshtml
@model IEnumerable<GShopConnection.product>

@{
    ViewBag.Title = "ViewProductByBraId";
    Layout = "~/Views/Shared/_GShopLayout.cshtml";
}
<div class="col-sm-3">
    <div class="left-sidebar">
        <h2>Category</h2>
        <div class="panel-group category-products" id="accordian">
            <!--category-productsr-->
            @Html.Action("Index", "Category")
        </div><!--/category-products-->

        <div class="brands_products">
            <!--brands_products-->
            <h2>Brands</h2>
            <div class="brands-name">
                <ul class="nav nav-pills nav-stacked">
                    @Html.Action("Index", "Brand")
                </ul>
            </div>
        </div><!--/brands_products-->

        <div class="price-range">
            <!--price-range-->
            <h2>Price Range</h2>
            <div class="well text-center">
                <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2"><br />
                <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
            </div>
        </div><!--/price-range-->

        <div class="shipping text-center">
            <!--shipping-->
            <img src="~/Assets/images/home/shipping.jpg" alt="" />
        </div><!--/shipping-->

    </div>
</div>
<div class="col-sm-9 padding-right">
    <div class="features_items">
        <!--features_items-->
        <h2 class="title text-center">Features Items</h2>
        @foreach (var item in Model)
        {
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center simpleCart_shelfItem">
                            <img src="@Url.Content("~/Assets/"+ @item.Image)" />
                            <h2 class="item_price">@String.Format(System.Globalization.CultureInfo.GetCultureInfo("vi-VN"), "{0:C0}", @item.Price)</h2>
                            <p style="min-height:50px" class="">@item.ProName</p>
                            <a href="#" class="btn btn-default add-to-cart item_add"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                            <a href="@Url.Action("Details", "Product", new { id = item.ProID})" class="btn btn-default add-to-cart"><span class="glyphicon glyphicon-list" aria-hidden="true"></span></a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div><!--features_items-->

    <div class="category-tab">
        <!--category-tab-->

    </div><!--/category-tab-->

    <div class="recommended_items">
        <!--recommended_items-->

    </div><!--/recommended_items-->

</div>

GShop/Views/Product/ViewProductByCatId.cshtml
@model IEnumerable<GShopConnection.product>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_GShopLayout.cshtml";
}
<div class="col-sm-3">
    <div class="left-sidebar">
        <h2>Category</h2>
        <div class="panel-group category-products" id="accordian">
            <!--category-productsr-->
            @Html.Action("Index", "Category")
        </div><!--/category-products-->

        <div class="brands_products">
            <!--brands_products-->
            <h2>Brands</h2>
            <div class="brands-name">
                <ul class="nav nav-pills nav-stacked">
                    @Html.Action("Index", "Brand")
                </ul>
            </div>
        </div><!--/brands_products-->

        <div class="price-range">
            <!--price-range-->
            <h2>Price Range</h2>
            <div class="well text-center">
                <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2"><br />
                <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
            </div>
        </div><!--/price-range-->

        <div class="shipping text-center">
            <!--shipping-->
            <img src="~/Assets/images/home/shipping.jpg" alt="" />
        </div><!--/shipping-->

    </div>
</div>
<div class="col-sm-9 padding-right">
    <div class="features_items">
        <!--features_items-->
        <h2 class="title text-center">Features Items</h2>
        @foreach (var item in Model)
        {
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center simpleCart_shelfItem">
                            <img src="@Url.Content("~/Assets/"+ @item.Image)" />
                            <h2 class="item_price">@String.Format(System.Globalization.CultureInfo.GetCultureInfo("vi-VN"), "{0:C0}", @item.Price)</h2>
                            <p style="min-height:50px" class="">@item.ProName</p>
                            <a href="#" class="btn btn-default add-to-cart item_add"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                            <a href="@Url.Action("Details", "Product", new { id = item.ProID})" class="btn btn-default add-to-cart"><span class="glyphicon glyphicon-list" aria-hidden="true"></span></a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div><!--features_items-->

    <div class="category-tab">
        <!--category-tab-->
        
    </div><!--/category-tab-->

    <div class="recommended_items">
        <!--recommended_items-->
        
    </div><!--/recommended_items-->

</div>