GShop/Areas/Admin/Controllers/AdminProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PetaPoco;
using GShopConnection;
using GShopBus.Bus;

namespace GShop.Areas.Admin.Controllers
{
    public class AdminProductController : Controller
    {
        //
        // GET: /Admin/AdminProduct/
        public ActionResult Index(int? page)
        {
            if (page == null)
            {
                page = 1;
            }
            return View(ProductBus.List(page));            
        }

        //
        // GET: /Admin/AdminProduct/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Admin/AdminProduct/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Admin/AdminProduct/Create
        [HttpPost]
        public ActionResult Create(product p)
        {
            try
            {
                // TODO: Add insert logic here
                ProductBus.Add(p);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Admin/AdminProduct/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Admin/AdminProduct/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Admin/AdminProduct/Delete/5        
        public ActionResult Delete(int id)
        {
            ProductBus.Remove(id);
                return RedirectToAction("Index");
        }
        
        //
        // POST: /Admin/AdminProduct/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

GShop/Areas/Admin/Views/AdminProduct/Create.cshtml
@model GShopConnection.product

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>product</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.ProID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProID)
                @Html.ValidationMessageFor(model => model.ProID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProName)
                @Html.ValidationMessageFor(model => model.ProName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TinyDes, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TinyDes)
                @Html.ValidationMessageFor(model => model.TinyDes)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullDes, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullDes)
                @Html.ValidationMessageFor(model => model.FullDes)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price)
                @Html.ValidationMessageFor(model => model.Price)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CatID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CatID)
                @Html.ValidationMessageFor(model => model.CatID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity)
                @Html.ValidationMessageFor(model => model.Quantity)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BraID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BraID)
                @Html.ValidationMessageFor(model => model.BraID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.View, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.View)
                @Html.ValidationMessageFor(model => model.View)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sold, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sold)
                @Html.ValidationMessageFor(model => model.Sold)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

GShop/Areas/Admin/Views/AdminProduct/Index.cshtml
@model PetaPoco.Page<GShopConnection.product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2 style ="color:red;">DANH SÁCH SẢN PHẨM</h2>

<div class="table-responsive">
    
    <div class="box-header">
        <h3 class="box-title">
            <a type="submit" class="btn btn-primary btn-lg" href="@Url.Action("Create", "AdminProduct")">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Thêm sản phẩm
            </a>
        </h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table id="sanpham" class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>STT</th>
                    <th>@Html.DisplayName("Tên Sản Phẩm")</th>
                    <th>@Html.DisplayName("Mô tả ngắn")</th>
                    <th>@Html.DisplayName("Mô tả đầy đủ")</th>
                    <th>@Html.DisplayName("Giá")</th>
                    <th>@Html.DisplayName("Mã Loại")</th>
                    <th>@Html.DisplayName("Số lượng")</th>
                    <th>@Html.DisplayName("Mã nhà sx")</th>
                    <th>@Html.DisplayName("Lượt xem")</th>
                    <th>@Html.DisplayName("Số lượng đã bán")</th>
                    <th>@Html.DisplayName("Sửa")</th>
                    <th>@Html.DisplayName("Xóa")</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Items)
                {
                    <tr>
                        <td>@item.ProID</td>
                        <td>@item.ProName</td>
                        <td>@item.TinyDes</td>
                        <td>@item.FullDes</td>
                        <td>@item.Price</td>
                        <td>@item.CatID</td>
                        <td>@item.Quantity</td>
                        <td>@item.BraID</td>
                        <td>@item.View</td>
                        <td>@item.Sold</td>
                        <th>
                            <a type="submit" class="btn btn-success" href="@Url.Action("Edit", "AdminProduct", new { id = item.ProID })">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            </a>

                        </th>
                        <th>
                            <a type="submit" class="btn btn-danger" href="@Url.Action("Delete", "AdminProduct", new { id = item.ProID })">
                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                            </a>
                        </th>
                    </tr>
                }
            </tbody>

        </table>
    </div>
    <div>
        @for (int i = 1; i <= Model.TotalPages; i++)
        {
            <ul class="pagination">
                <li><a href="?page=@i"> @i </a></li>
            </ul>
        }
    </div>
    <!-- /.box-body -->
</div>